/// <reference lib="deno.ns" />

import { dirname, fromFileUrl, join } from "jsr:@std/path@1"

const root = dirname(dirname(fromFileUrl(import.meta.url)))
const readmePath = join(root, "../vendor/ts-pattern/README.md")
const outputPath = join(root, "src/generated/readme-examples.ts")

const readme = await Deno.readTextFile(readmePath)

const headingBefore = (index: number) =>
  readme
    .slice(0, index)
    .split("\n")
    .reverse()
    .find((line: string) => /^#{2,6}\s+/.test(line))
    ?.replace(/^#{2,6}\s+/, "")
    .replace(/`/g, "")
    .trim() ?? "README example"

const slugify = (value: string) =>
  value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "") || "example"

const usesTsPattern = (code: string) =>
  /\b(match|isMatching)\s*(?:<[^;{}]*>)?\(/.test(code) || /\bP\./.test(code) ||
  /\bPattern\./.test(code)

const hasPlaceholder = (code: string) =>
  /(^|[^.])\.\.\.([^.]|$)/.test(code) ||
  code.includes("match(...") ||
  code.includes(".with(...") ||
  code.includes("MyCustomError") ||
  code.includes("value = ...")

const isApiSignature = (code: string) =>
  /^\s*(?:export\s+)?function\s+\w+/.test(code) ||
  /^\s*match\([^\n]*\);?\s*$/.test(code)

const readsUndeclaredInput = (code: string) =>
  code.includes("match(input)") &&
  !/(?:const|let|var|function|declare\s+const)\s+input\b/.test(code) &&
  !/\(input[):,\s]/.test(code)

const readsUndeclaredValue = (code: string) =>
  (code.includes("isBlogPost(value)") ||
    code.includes("isMatching(blogPostPattern, value)")) &&
  !/(?:const|let|var|declare\s+const)\s+value\b/.test(code)

const usesExternalRuntimeInput = (code: string) =>
  code.includes("someUrl") || code.includes("fetch(")

const shouldInclude = (language: string, code: string) =>
  ["ts", "typescript"].includes(language) &&
  usesTsPattern(code) &&
  !code.trimStart().startsWith(".") &&
  !hasPlaceholder(code) &&
  !isApiSignature(code) &&
  !code.includes("declare const") &&
  !code.includes("@ts-expect-error") &&
  !code.includes("❌") &&
  !readsUndeclaredInput(code) &&
  !readsUndeclaredValue(code) &&
  !usesExternalRuntimeInput(code)

const ensureImport = (code: string) => {
  if (
    code.includes("from 'ts-pattern'") || code.includes('from "ts-pattern"')
  ) {
    return code
  }

  const imports = [
    code.includes("isMatching") ? "isMatching" : undefined,
    code.includes("match(") ? "match" : undefined,
    /\bP\./.test(code) ? "P" : undefined,
    /\bPattern\./.test(code) ? "Pattern" : undefined,
  ].filter(Boolean).join(", ")

  return imports ? `import { ${imports} } from 'ts-pattern';\n\n${code}` : code
}

const examples = [...readme.matchAll(/```(\w+)\n([\s\S]*?)```/g)]
  .map((match, index) => ({
    language: match[1],
    code: match[2].trim(),
    heading: headingBefore(match.index ?? 0),
    index,
  }))
  .filter(({ language, code }) => shouldInclude(language, code))
  .map(({ code, heading, index }) => ({
    id: `readme-${index}-${slugify(heading)}`,
    label: `README: ${heading}`,
    source: ensureImport(code).replace(/'ts-pattern'/g, '"ts-pattern"'),
  }))

await Deno.mkdir(dirname(outputPath), { recursive: true })
await Deno.writeTextFile(
  outputPath,
  `// Generated by web/scripts/generate-readme-examples.ts from vendor/ts-pattern/README.md.\n` +
    `export const readmeExamples = ${
      JSON.stringify(examples, null, 2)
    } as const\n`,
)

console.log(`Generated ${examples.length} README examples`)
