/// <reference lib="deno.ns" />

import { dirname, fromFileUrl, join } from "jsr:@std/path@1"

const root = dirname(dirname(fromFileUrl(import.meta.url)))
const readmePath = join(root, "../vendor/ts-pattern/README.md")
const outputPath = join(root, "src/generated/readme-examples.ts")

const readme = await Deno.readTextFile(readmePath)

const headingBefore = (index: number) =>
  readme
    .slice(0, index)
    .split("\n")
    .reverse()
    .find((line: string) => /^#{2,6}\s+/.test(line))
    ?.replace(/^#{2,6}\s+/, "")
    .replace(/`/g, "")
    .trim() ?? "README example"

const slugify = (value: string) =>
  value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "") || "example"

const shouldInclude = (language: string, code: string) =>
  ["ts", "typescript"].includes(language) &&
  code.includes("match(") &&
  code.includes(".with(") &&
  (code.includes(".otherwise(") || code.includes(".exhaustive(")) &&
  !code.includes("...") &&
  !code.includes("match(...") &&
  !code.includes(".with(...") &&
  !code.includes(".returnType") &&
  !code.includes(".narrow") &&
  !code.includes(".run()") &&
  !code.includes("Pattern.") &&
  !code.includes("P.any") &&
  !code.includes("NaN") &&
  !code.includes("P.select") &&
  !code.includes("P.record") &&
  !code.includes("P.set") &&
  !code.includes("P.map") &&
  !code.includes("P.intersection") &&
  !/P\.(string|number|bigint)\./.test(code) &&
  !code.includes("...P.array")

const ensureImport = (code: string) =>
  code.includes("from 'ts-pattern'") || code.includes('from "ts-pattern"')
    ? code
    : `import { match, P } from 'ts-pattern';\n\n${code}`

const ensureInputDeclaration = (code: string) =>
  code.includes("type Input") &&
    code.includes("match(input)") &&
    !/(?:const|let|var|declare\s+const)\s+input\b/.test(code)
    ? code.replace(
      /\nconst output = match\(input\)/,
      "\ndeclare const input: Input;\n\nconst output = match(input)",
    )
    : code

const examples = [...readme.matchAll(/```(\w+)\n([\s\S]*?)```/g)]
  .map((match, index) => ({
    language: match[1],
    code: match[2].trim(),
    heading: headingBefore(match.index ?? 0),
    index,
  }))
  .filter(({ language, code }) => shouldInclude(language, code))
  .map(({ code, heading, index }) => ({
    id: `readme-${index}-${slugify(heading)}`,
    label: `README: ${heading}`,
    source: ensureInputDeclaration(ensureImport(code)).replace(
      /'ts-pattern'/g,
      '"ts-pattern"',
    ),
  }))

await Deno.mkdir(dirname(outputPath), { recursive: true })
await Deno.writeTextFile(
  outputPath,
  `// Generated by web/scripts/generate-readme-examples.ts from vendor/ts-pattern/README.md.\n` +
    `export const readmeExamples = ${
      JSON.stringify(examples, null, 2)
    } as const\n`,
)

console.log(`Generated ${examples.length} README examples`)
